os: linux
dist: trusty
python: '3.4'
sudo: required
language: generic
python: 3.5
cache: apt

before_install:
  - sudo pip install --upgrade pip pipenv

before_script:
  - pipenv install -v

script:
  - pipenv run "catkin build -v"
