os: linux
dist: trusty
sudo: required
language: python
python: "3.6"
env: PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - sudo pip install --upgrade pip pipenv

before_script:
  - pipenv install -v

script:
  # Use a script stored in the Pipfile of the repo.
  - pipenv run catkin_build
