os: linux
dist: trusty
python: '3.4'
sudo: required
language: generic
cache: apt
python: "3.5"
env: PYTHON=/usr/bin/python3.5

before_install:
  - sudo pip install --upgrade pip pipenv

before_script:
  - pipenv install -v

script:
  - pipenv run "catkin build -v"
